/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2016-09-07 00:35:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>SmartCompras</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/cosmo/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/estilo.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Catamaran|Hammersmith+One|Imprima\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.0/jqueryui.js\"></script> \r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script> \r\n");
      out.write("<script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script> \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "topo.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"col-sm-4\">    \r\n");
      out.write("\t<div class=\"panel panel-default\">    \r\n");
      out.write("\t\t <div class=\"panel panel-heading\">      \r\n");
      out.write("\t\t \t<div class=\"panel-title\">       Listas Páticas    \r\n");
      out.write("\t\t \t</div>     \r\n");
      out.write("\t\t </div>     \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t <div class=\"panel-body\">   \r\n");
      out.write("\t\t <p>Você precisa fazer um churrasco para amigos e não sabe por onde começar? Resolvemos esse problema pra você. \r\n");
      out.write("\t\t Com apenas poucos passos, você terá toda lista pronta de acordo com o número de convidados.</p>   \r\n");
      out.write("\t\t</div>    \r\n");
      out.write("\t</div>   \r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-sm-4\">    \r\n");
      out.write("\t<div class=\"panel panel-default\">    \r\n");
      out.write("\t\t <div class=\"panel panel-heading\">      \r\n");
      out.write("\t\t \t<div class=\"panel-title\">      Localize-se \r\n");
      out.write("\t\t \t</div>     \r\n");
      out.write("\t\t </div>     \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t <div class=\"panel-body\">   \r\n");
      out.write("\t\t <p>Utilize nosso localizador e chegue de \r\n");
      out.write("\t\t forma mais rápida ao local que possui a lista de acordo com suas preferências</p> <br/>  <br/>\r\n");
      out.write("\t\t</div>    \r\n");
      out.write("\t</div>   \r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-sm-4\">    \r\n");
      out.write("\t<div class=\"panel panel-default\">    \r\n");
      out.write("\t\t <div class=\"panel panel-heading\">      \r\n");
      out.write("\t\t \t<div class=\"panel-title\">      Acompanhe\r\n");
      out.write("\t\t \t</div>     \r\n");
      out.write("\t\t </div>     \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t <div class=\"panel-body\">   \r\n");
      out.write("\t\t <p>Verifique seus gastos através de gráficos. \r\n");
      out.write("\t\t Uma forma simples e fácil de fazer o planejamento de gastos familiar.</p> <br/> <br/>\r\n");
      out.write("\t\t</div>    \r\n");
      out.write("\t</div>   \r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-sm-4\">    \r\n");
      out.write("\t<div class=\"panel panel-default\">    \r\n");
      out.write("\t\t <div class=\"panel panel-heading\">      \r\n");
      out.write("\t\t \t<div class=\"panel-title\">       Listas Páticas    \r\n");
      out.write("\t\t \t</div>     \r\n");
      out.write("\t\t </div>     \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t <div class=\"panel-body\">   \r\n");
      out.write("\t\t <p>Você precisa fazer um churrasco para amigos e não sabe por onde começar? Resolvemos esse problema pra você. \r\n");
      out.write("\t\t Com apenas poucos passos, você terá toda lista pronta de acordo com o número de convidados.</p>   \r\n");
      out.write("\t\t</div>    \r\n");
      out.write("\t</div>   \r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-sm-4\" id=\"pular\">    \r\n");
      out.write("\t<div class=\"panel panel-default\">    \r\n");
      out.write("\t\t <div class=\"panel panel-heading\">      \r\n");
      out.write("\t\t \t<div class=\"panel-title\">       Listas Páticas    \r\n");
      out.write("\t\t \t</div>     \r\n");
      out.write("\t\t </div>     \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t <div class=\"panel-body\">   \r\n");
      out.write("\t\t <p>Você precisa fazer um churrasco para amigos e não sabe por onde começar? Resolvemos esse problema pra você. \r\n");
      out.write("\t\t Com apenas poucos passos, você terá toda lista pronta de acordo com o número de convidados.</p>   \r\n");
      out.write("\t\t</div>    \r\n");
      out.write("\t</div>   \r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-sm-4\">    \r\n");
      out.write("\t<div class=\"panel panel-default\">    \r\n");
      out.write("\t\t <div class=\"panel panel-heading\">      \r\n");
      out.write("\t\t \t<div class=\"panel-title\">       Listas Páticas    \r\n");
      out.write("\t\t \t</div>     \r\n");
      out.write("\t\t </div>     \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t <div class=\"panel-body\">   \r\n");
      out.write("\t\t <p>Você precisa fazer um churrasco para amigos e não sabe por onde começar? Resolvemos esse problema pra você. \r\n");
      out.write("\t\t Com apenas poucos passos, você terá toda lista pronta de acordo com o número de convidados.</p>   \r\n");
      out.write("\t\t</div>    \r\n");
      out.write("\t</div>   \r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
