/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2016-09-06 23:32:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class topo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>SmartCompras</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/cosmo/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/estilo.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Catamaran|Hammersmith+One|Imprima\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.0/jqueryui.js\"></script> \r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script> \r\n");
      out.write("<script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script> \r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Container  -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"jumbotron\">\r\n");
      out.write("\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-primary \" data-toggle=\"modal\" data-target=\"#logar\"> Login </button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-default \" data-toggle=\"modal\" data-target=\"#cadastro\">  Cadastrar</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br/> <br/>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t  <h1>SmartCompras</h1>\r\n");
      out.write("\t\t  <p>Uma forma mais prática e eficiente de pesquisar os preços de sua lista de compras sem precisar sair do seu conforto.  \r\n");
      out.write("\t\t  Nossa aplicação informa o lugar mais próximo e também o mais barato.</p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<center><a href=\"#pular\" class=\"btn btn-primary  btn-block\">Saiba mais</a></center>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("<!--  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Modal Logar -->\r\n");
      out.write("\r\n");
      out.write("\t \r\n");
      out.write("  <!-- Trigger the modal with a button -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Modal -->\r\n");
      out.write("  <div class=\"modal\" style=\"margin-top: 50px;\" id=\"logar\" role=\"dialog\">\r\n");
      out.write("   <div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t <div class=\"modal-header\">\r\n");
      out.write("\t\t\t \t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t \t<h4 class=\"modal-title\">Login</h4>\r\n");
      out.write("        \t </div>\r\n");
      out.write("        \t \r\n");
      out.write("        \t  <div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t<form class=\"form-horizontal\">\r\n");
      out.write("\t\t\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t      <label for=\"inputEmail\" class=\"col-lg-2 control-label\">Email</label>\r\n");
      out.write("\t\t\t\t\t      <div class=\"col-lg-10\">\r\n");
      out.write("\t\t\t\t\t        <input type=\"text\" class=\"form-control\" id=\"inputEmail\" placeholder=\"Digite seu Email\">\r\n");
      out.write("\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t      <label for=\"inputPassword\" class=\"col-lg-2 control-label\">Senha</label>\r\n");
      out.write("\t\t\t\t\t      <div class=\"col-lg-10\">\r\n");
      out.write("\t\t\t\t\t        <input type=\"password\" class=\"form-control\" id=\"inputPassword\" placeholder=\"Digite sua Password\">\r\n");
      out.write("\t\t\t\t\t       \r\n");
      out.write("\t\t\t\t\t        <div class=\"esqueceu\">\r\n");
      out.write("\t\t\t\t\t          <label>\r\n");
      out.write("\t\t\t\t\t            <a href=\"#\">Esqueceu a senha? </a>\r\n");
      out.write("\t\t\t\t\t          </label>\r\n");
      out.write("\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t </form>\t\r\n");
      out.write("\t\t\t\t\t</div>  \r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">  \r\n");
      out.write("\t\t\t\t\t    <div class=\"form-group\">\r\n");
      out.write("      \t\t\t\t\t\t<div class=\"col-lg-10 col-lg-offset-2\">\r\n");
      out.write("        \t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-warning\">Logar</button>\r\n");
      out.write("      \t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Fim logar -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Modal Cadastrar -->\r\n");
      out.write("\r\n");
      out.write("\t \r\n");
      out.write("  <!-- Trigger the modal with a button -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Modal -->\r\n");
      out.write("  <div class=\"modal\" style=\"margin-top: 50px;\" id=\"cadastro\" role=\"dialog\">\r\n");
      out.write("   <div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t <div class=\"modal-header\">\r\n");
      out.write("\t\t\t \t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t \t<h4 class=\"modal-title\">Cadastrar</h4>\r\n");
      out.write("        \t </div>\r\n");
      out.write("        \t \r\n");
      out.write("        \t  <div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t<form class=\"form-horizontal\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t      <label for=\"inputNome\" class=\"col-lg-2 control-label\">Nome</label>\r\n");
      out.write("\t\t\t\t\t      <div class=\"col-lg-10\">\r\n");
      out.write("\t\t\t\t\t        <input type=\"text\" class=\"form-control\" id=\"inputNome\" placeholder=\"Digite seu Nome\">\r\n");
      out.write("\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t      <label for=\"inputSobrenome\" class=\"col-lg-2 control-label\">Sobrenome</label>\r\n");
      out.write("\t\t\t\t\t      <div class=\"col-lg-10\">\r\n");
      out.write("\t\t\t\t\t        <input type=\"text\" class=\"form-control\" id=\"inputSobrenome\" placeholder=\"Digite seu Sobrenome\">\r\n");
      out.write("\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t      <label for=\"inputEnd\" class=\"col-lg-2 control-label\">Endereço</label>\r\n");
      out.write("\t\t\t\t\t      <div class=\"col-lg-10\">\r\n");
      out.write("\t\t\t\t\t        <input type=\"text\" class=\"form-control\" id=\"inputEnd\" placeholder=\"Digite seu Sobrenome\">\r\n");
      out.write("\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t      <label for=\"inputTel\" class=\"col-lg-2 control-label\">Telefone</label>\r\n");
      out.write("\t\t\t\t\t      <div class=\"col-lg-10\">\r\n");
      out.write("\t\t\t\t\t        <input type=\"text\" class=\"form-control\" id=\"inputTel\" placeholder=\"Digite seu Telefone\">\r\n");
      out.write("\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t      <label for=\"inputNasc\" class=\"col-lg-2 control-label\">Nascimento</label>\r\n");
      out.write("\t\t\t\t\t      <div class=\"col-lg-10\">\r\n");
      out.write("\t\t\t\t\t        <input type=\"text\" class=\"form-control\" id=\"inputNasc\" placeholder=\"Digite sua Data de nascimento\">\r\n");
      out.write("\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t      <label for=\"inputEmail\" class=\"col-lg-2 control-label\">Email</label>\r\n");
      out.write("\t\t\t\t\t      <div class=\"col-lg-10\">\r\n");
      out.write("\t\t\t\t\t        <input type=\"text\" class=\"form-control\" id=\"inputEmail\" placeholder=\"Digite seu Email\">\r\n");
      out.write("\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t      <label for=\"inputPassword\" class=\"col-lg-2 control-label\">Senha</label>\r\n");
      out.write("\t\t\t\t\t      <div class=\"col-lg-10\">\r\n");
      out.write("\t\t\t\t\t        <input type=\"password\" class=\"form-control\" id=\"inputPassword\" placeholder=\"Digite sua Password\">\r\n");
      out.write("\t\t\t\t\t       \r\n");
      out.write("\t\t\t\t\t        \r\n");
      out.write("\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t </form>\t\r\n");
      out.write("\t\t\t\t\t</div>  \r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">  \r\n");
      out.write("\t\t\t\t\t    <div class=\"form-group\">\r\n");
      out.write("      \t\t\t\t\t\t<div class=\"col-lg-10 col-lg-offset-2\">\r\n");
      out.write("        \t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-warning\">Logar</button>\r\n");
      out.write("      \t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Fim logar -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
